config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('materials/', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import contact, StudentListView, StudentDetailsView, StudentCreateView, StudentUpdateView, \
    StudentDeleteView, toggle_activity

app_name = MainConfig.name

urlpatterns = [
    path('', StudentListView.as_view(), name='index'),
    path('contact/', cache_page(60)(contact), name='contact'),
    path('view/<int:pk>/', StudentDetailsView.as_view(), name='view_student'),
    path('create/', StudentCreateView.as_view(), name='create_student'),
    path('edit/<int:pk>/', StudentUpdateView.as_view(), name='update_student'),
    path('delete/<int:pk>/', StudentDeleteView.as_view(), name='delete_student'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

main/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Student(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    avatar = models.ImageField(upload_to='students/', verbose_name='аватар', **NULLABLE)

    email = models.CharField(max_length=150, verbose_name='email', unique=True, **NULLABLE)

    is_activ = models.BooleanField(default=True, verbose_name='учится')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'студент'
        verbose_name_plural = 'студенты'
        ordering = ('last_name',)


class Subject(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    description = models.TextField(verbose_name='описание')

    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='студент')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'предмет'
        verbose_name_plural = 'предметы'

main/forms.py
from django import forms

from main.models import Student, Subject


class StyleForMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class StudentForm(StyleForMixin, forms.ModelForm):
    class Meta:
        model = Student
        # fields = '__all__'
        fields = ('first_name', 'last_name', 'avatar', 'email',)
        # exclude = ('is_activ',)

    def clean_email(self):
        cleaned_data = self.cleaned_data['email']

        if 'sky.pro' not in cleaned_data:
            raise forms.ValidationError('почта должна относиться к учебному заведению')

        return cleaned_data


class SubjectForm(StyleForMixin, forms.ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'

main/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, \
    UserPassesTestMixin
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from main.forms import StudentForm, SubjectForm
from main.models import Student, Subject
from main.templates.main.services import get_cache_subject_for_student


class StudentListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Student
    permission_required = 'main.view_student'


@login_required
def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        print(f'Имя - {name} email({email}): сообщение({message})')

    context = {
        'title': 'Контакты'
    }

    return render(request, 'main/contact.html', context)


class StudentDetailsView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Student
    permission_required = 'main.view_student'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        context_data['subjects'] = get_cache_subject_for_student(self.object.pk)
        return context_data


class StudentCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Student
    form_class = StudentForm
    # fields = ('first_name', 'last_name', 'avatar')
    permission_required = 'main.add_student'
    success_url = reverse_lazy('main:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Student, Subject, form=SubjectForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = SubjectFormset(self.request.POST)
        else:
            context_data['formset'] = SubjectFormset()
        return context_data


class StudentUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Student
    form_class = StudentForm
    permission_required = 'main.change_student'
    # fields = ('first_name', 'last_name', 'avatar')
    success_url = reverse_lazy('main:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Student, Subject, form=SubjectForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = SubjectFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = SubjectFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object

        formset.save()

        return super().form_valid(form)


class StudentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Student
    success_url = reverse_lazy('main:index')

    def test_func(self):
        return self.request.user.is_superuser


def toggle_activity(request, pk):
    student_item = get_object_or_404(Student, pk=pk)
    if student_item.is_activ:
        student_item.is_activ = False
    else:
        student_item.is_activ = True

    student_item.save()

    return redirect(reverse('main:index'))

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
            </div>

          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Album</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
              {% include 'main/includes/inc_main_menu.html' %}
          </button>
        </div>
      </div>

    </header>


    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
              {% block content %}
              {% endblock %}
          </div>
        </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
        </p>
        <p>&copy; 2023 - {% now 'Y' %}</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
  </body>
</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                Офис МСК<br>
                Офис СПб
            </p>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <h2>Напишите нам</h2>
            <form method="post">
                {% csrf_token %}
                <input class="form-control mb-2" name="name"/>
                <input class="form-control mb-2" name="email"/>
                <textarea class="form-control" name="email"></textarea>
                <button type="submit" class="btn btn-primary form-control">Отправить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/student_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить студента "{{ object.first_name }} {{ object.last_name }}" ?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'main:index' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/student_detail.html
{#{% load my_tags %}#}
{%  extends 'main/base.html'%}

{% block content %}
    <div class="container">
        <div class="card mb-4 box-shadow ">
            <div class="card-header d-flex align-items-center justify-content-center h-80">
                <h5 class="my-0 font-weight-normal text-truncate">Иноформация студента</h5>
            </div>
            <div class="card-body flex-column">
                  <div class="row align-items-start">
                    <div class="col">
                      Имя
                    </div>
                    <div class="col">
                      {{ object.first_name }}
                    </div>
                  </div>
                  <div class="row align-items-center">
                    <div class="col">
                      Фамилия
                    </div>
                    <div class="col">
                      {{ object.last_name }}
                    </div>
                  </div>
                  <div class="row align-items-end">
                    <div class="col">
                      Почта
                    </div>
                  </div>
                <div class="col-6">
                    <img src="/media/{{ object.avatar }}"/>
                </div>
            </div>
        </div>
        <div class="card mb-4 box-shadow ">
            <div class="card-header d-flex align-items-center justify-content-center h-80">
                <h5 class="my-0 font-weight-normal text-truncate">Предметы студента</h5>
            </div>
            <div class="card-body flex-column">
                  <div class="row align-items-start">
                      <ul>
                          {% for subject in subjects %}
                            <li>{{ subject }}</li>
                          {% endfor %}
                      </ul>
                  </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/student_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">

                <div class="card">
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                        {% if object %}
                            <button type="submit" class="btn btn-primary">Добавить</button>
                        {% else %}
                            <button type="submit" class="btn btn-primary">Создать</button>
                        {% endif %}
                    </div>
                </div>
            </form>

        </div>
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">

                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ formset.menegement_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% if not forloop.last %}
                            <hr>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

main/templates/main/student_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    {% if perms.main.add_student %}
    <a class="btn btn-outline-primary" href="{% url 'main:create_student' %}">Добавить студента</a>
    {% endif %}
</div>

{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {% if object.is_activ %}
                {{ object|title }}
                {% else %}
                <span class="text_muted">{{ object }}</span>
                {% endif %}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if perms.main.view_student %}
                    <a href="{% url 'main:view_student' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">View</a>
                    {% endif %}
                    {% if perms.main.change_student %}
                    <a href="{% url 'main:update_student' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Edit</a>
                    {% endif %}
                    {% if user.is_superuser %}
                    <a href="{% url 'main:delete_student' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Delete</a>
                    {% endif %}
                </div>
                {% if object.is_activ %}
                <a class="btn btn-warning" href="{% url 'main:toggle_activity' object.pk %}">Деактивировать</a>
                {% else %}
                <a class="btn btn-success" href="{% url 'main:toggle_activity' object.pk %}">Активировать</a>
                {% endif %}
                <small class="text-muted"></small>
            </div>
            <small class="text-muted"></small>
        </div>
    </div>
</div>
</div>
{% endfor %}
{% endblock %}